### ISSUE TITLE
Negative number is also supported in the donation value

### ISSUE THREAD

**Issue by niraj-adhikari** [losers/tree#50]
Providing negative number like -10 and clicking on 'Donate Now' button shows a never ending loading icon.

**Comment by niraj-adhikari** [comment]
adding `min="1"` attribute inside input tag seems to do the trick. ;)

**Comment by varunkumarmedam** [comment]
Verified at [beta.bloodline.app/test/donations](https://beta.bloodline.app/app/test/donations) user cant put '-' in the input box

**Comment by niraj-adhikari** [comment]
Negative numbers can still be set with the (down) arrow button.
![GIF02](https://user-images.githubusercontent.com/87991295/127512671-9637f462-f480-4e1b-8b6d-080fb2895a29.gif)
