### ISSUE TITLE
PIN code should not be exposed while typing

### ISSUE THREAD

**Issue by niraj-adhikari** [losers/tree#52]
PIN code should be treated as password and hidden while typing. Additionally, we can provide an option to view the PIN with and eye icon that displays the entered PIN.

**Comment by varunkumarmedam** [comment]
Do we need to hide pins while creating a family tree and also in updating? what do you think?

**Comment by varunkumarmedam** [comment]
@niraj-adhikari have a look at beta.bloodline.app and let us know if need any more improvement there
